# -*- coding: utf-8 -*-
"""mid_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aK6y-Hy7mUUiU5nnTiRkkxORTaTjOwL

# Setup:
"""

# ── All imports in one place ──────────────────────────────────────────

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    mean_absolute_error
)

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    log_loss,
    classification_report
)

from sklearn.preprocessing import LabelEncoder

from sklearn.tree import (
    DecisionTreeClassifier,
    plot_tree,
    export_text
)

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)


print('Ready ✅')

# Load dataset — each row is a student, each column is a feature
df = pd.read_csv('game_characters.csv')
print(f'Dataset: {df.shape[0]} , {df.shape[1]} columns')
df.head(8)

"""# Task1 : label encoder for race column"""

# 0 Dragon , 1 Dwarf , 2 Elf , 3 Human , 4 Orc
from sklearn.preprocessing import LabelEncoder

game_characters_enc = df.copy()
le = LabelEncoder()

game_characters_enc['race'] = le.fit_transform(game_characters_enc['race'])

game_characters_enc.head(10)

"""## make standard scaler:"""

# Select numerical columns (excluding the target/categorical columns if needed)
numerical_cols = ['level', 'strength', 'agility', 'intellect', 'stamina',
                   'magic_affinity', 'years_training' ]

scaler = StandardScaler()

game_characters_scaled = game_characters_enc.copy()
game_characters_scaled[numerical_cols] = scaler.fit_transform(game_characters_scaled[numerical_cols])

game_characters_scaled.head(20)

"""# Task 3 :"""

# Quick look at both features vs Salary
plt.scatter(df['race'], df['power_score'], color='steelblue')
plt.xlabel('race')
plt.ylabel('power_score')
plt.show()

"""##ploting:"""

# Quick look at both features vs Salary
plt.scatter(df['level'], df['power_score'], color='steelblue')
plt.xlabel('level')
plt.ylabel('power_score')
plt.show()

"""## Linear Regrassion  :"""

from sklearn.model_selection import train_test_split
X = game_characters_scaled[['race', 'level', 'strength', 'agility','intellect','stamina','magic_affinity','years_training']]
y = game_characters_scaled['power_score']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


print(f'Train: {len(X_train)} rows  |  Test: {len(X_test)} rows')

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.3f}")
print(f"MAE:  {mae:.3f}")
print(f"R²:   {r2:.3f}")

print("\nIntercept:", model.intercept_)
for feature, coef in zip(X.columns, model.coef_):
    print(f"  {feature:<16} {coef:.4f}")

"""### decision tree regressor"""

# ============================================================
# Task 3 — Regression: Predict power_score
# ============================================================
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

# 1. تحميل البيانات
df = pd.read_csv('game_characters.csv')

X = df[['race', 'level', 'strength', 'agility','intellect','stamina','magic_affinity','years_training']]
X = pd.get_dummies(X, columns=['race'], drop_first=False)  # encode race
y = df['power_score']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

results = {}

# ============================================================
# 2. Linear Regression
# ============================================================
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
y_pred_lin = lin_reg.predict(X_test)
results['Linear Regression'] = r2_score(y_test, y_pred_lin)

# ============================================================
# 3. Polynomial Regression (degree 2)
# ============================================================
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

poly_reg = LinearRegression()
poly_reg.fit(X_train_poly, y_train)
y_pred_poly = poly_reg.predict(X_test_poly)
results['Polynomial Regression (deg=2)'] = r2_score(y_test, y_pred_poly)

# ============================================================
# 4. Decision Tree Regressor
# ============================================================
tree_reg = DecisionTreeRegressor(max_depth=4, random_state=42)
tree_reg.fit(X_train, y_train)
y_pred_tree = tree_reg.predict(X_test)
results['Decision Tree Regressor'] = r2_score(y_test, y_pred_tree)

# ============================================================
# 5. Compare R² scores
# ============================================================
print("R² Score Comparison:")
for model, score in sorted(results.items(), key=lambda x: -x[1]):
    print(f"  {model:<30} {score:.4f}")

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

plt.figure(figsize=(20, 10))
plot_tree(
    tree_reg,
    feature_names=X.columns,
    filled=True,
    rounded=True,
    fontsize=9
)
plt.title("Decision Tree Regressor - Predicting Power Score", fontsize=14)
plt.tight_layout()
plt.savefig('decision_tree_regressor.png', dpi=150, bbox_inches='tight')
plt.show()

def predict_score(race, level, strength, agility, intellect, stamina, magic_affinity, years_training):
    # Build a single-row DataFrame with the same raw columns used in training
    new_char = pd.DataFrame([{
        'race': race,
        'level': level,
        'strength': strength,
        'agility': agility,
        'intellect': intellect,
        'stamina': stamina,
        'magic_affinity': magic_affinity,
        'years_training': years_training
    }])

    # One-hot encode race the same way as training data
    new_char = pd.get_dummies(new_char, columns=['race'], drop_first=False)

    # Align columns with X_train — adds any missing race_* columns as 0,
    # drops any extra ones, and keeps the exact same column order
    new_char = new_char.reindex(columns=X_train.columns, fill_value=0)

    # Predict using whichever regressor you want (e.g. rf_reg, tree_reg, lin_reg)
    prediction = rf_reg.predict(new_char)[0]
    return prediction

# Example usage
score = predict_score(
    race='Dragon',
    level=40,
    strength=90,
    agility=50,
    intellect=45,
    stamina=100,
    magic_affinity=0.3,
    years_training=20
)
print(f"Predicted power_score: {score:.2f}")

"""# Task4:

## multi _ Class _ classification:
"""

# How many students per grade?
df['role'].value_counts()

# Prepare features and target for multi-class
# Features (X) = what the model uses to make a prediction
# Target (y)   = what we want to predict

X = game_characters_scaled[['race', 'level', 'strength', 'agility','intellect','stamina','magic_affinity','years_training']]
y = game_characters_scaled['role']

# Split: 80% to train the model, 20% to test it
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f'Training samples : {len(X_train)}')
print(f'Testing  samples : {len(X_test)}')

# Train a Logistic Regression model on 4 classes
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

print('Predictions for the first 10 test students:')
comparison = pd.DataFrame({'Actual': y_test.values[:10], 'Predicted': y_pred[:10]})
print(f'Actual: {y_test.values[:10]}')
print(f'Predicted: {y_pred[:10]}')

# The model can also give a PROBABILITY for each class
# This is the softmax output — all probabilities sum to 1

proba = model.predict_proba(X_test)

print('Predicted class probabilities for the first 5 students:')
proba.round(2)[:5]

# Cross-entropy loss — one line with sklearn
loss = log_loss(y_test, proba)
print(f'Cross-Entropy Loss: {loss:.4f}')
print()
print('Interpretation:')
print('  < 0.3  → model is very confident and mostly right')
print('  0.3–1  → decent, some uncertainty')
print('  > 1    → model is confused or overconfident in wrong answers')

"""### Confusion Matrix


"""

# Confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=['Warrior', 'Archer', 'Healer', 'Mage'])

plt.figure(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Warrior', 'Archer', 'Healer', 'Mage'])
disp.plot(cmap='Blues', colorbar=False)
plt.title('Confusion Matrix — role Prediction')
plt.tight_layout()
plt.show()

# Accuracy, Precision, Recall, F1 — all in one
print('=== Classification Report ===')
print(classification_report(y_test, y_pred, target_names=['Warrior', 'Archer', 'Healer', 'Mage']))

print('=== Individual Metrics ===')
print(f'Accuracy  : {accuracy_score(y_test, y_pred):.2%}  — overall % correct')
print(f'Precision : {precision_score(y_test, y_pred, average="macro"):.2%}  — when it says a class, how often is it right?')
print(f'Recall    : {recall_score(y_test, y_pred, average="macro"):.2%}  — of the real class, how many did it catch?')
print(f'F1 Score  : {f1_score(y_test, y_pred, average="macro"):.2%}  — balance between precision & recall')

"""## Decision Tree classifier:"""

# ============================================================
# Task 4 — Classification: Predict role
# ============================================================
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


X = df[['race', 'level', 'strength', 'agility','intellect','stamina','magic_affinity','years_training']]
X = pd.get_dummies(X, columns=['race'], drop_first=False)  # encode race
y = df['role']  # target

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

results = {}

# ============================================================
# 2. Logistic Regression
# ============================================================
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)
y_pred_log = log_reg.predict(X_test)
results['Logistic Regression'] = accuracy_score(y_test, y_pred_log)

print("=== Logistic Regression ===")
print(f"Accuracy: {results['Logistic Regression']:.4f}")
print(classification_report(y_test, y_pred_log))

# ============================================================
# 3. Decision Tree Classifier
# ============================================================
tree_clf = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=4,
    random_state=42
)
tree_clf.fit(X_train, y_train)
y_pred_tree = tree_clf.predict(X_test)
results['Decision Tree Classifier'] = accuracy_score(y_test, y_pred_tree)

print("\n=== Decision Tree Classifier ===")
print(f"Accuracy: {results['Decision Tree Classifier']:.4f}")
print(classification_report(y_test, y_pred_tree))

# ============================================================
# 4. Compare Accuracy Scores
# ============================================================
print("\nAccuracy Comparison:")
for model, score in sorted(results.items(), key=lambda x: -x[1]):
    print(f"  {model:<28} {score:.4f}")

# ============================================================
# 5. Confusion Matrix + Tree Plot (optional visuals)
# ============================================================
labels = sorted(y.unique())
cm = confusion_matrix(y_test, y_pred_tree, labels=labels)
print("\nDecision Tree Confusion Matrix:")
print(pd.DataFrame(cm, index=labels, columns=labels))

plt.figure(figsize=(20, 10))
plot_tree(
    tree_clf,
    feature_names=X.columns,
    class_names=[str(c) for c in tree_clf.classes_],
    filled=True,
    rounded=True,
    fontsize=9
)
plt.title("Decision Tree Classifier - Predicting Role", fontsize=14)
plt.tight_layout()
plt.savefig('decision_tree_classifier_role.png', dpi=150, bbox_inches='tight')
plt.show()

"""# Task5 :"""

# ============================================================
# Task 5 — Analysis
# ============================================================

# --- 1. Which race has the highest average power_score? ---
avg_power_by_race = df.groupby('race')['power_score'].mean().sort_values(ascending=False)
print("Average power_score by race:")
print(avg_power_by_race)
print(f"\n>>> Highest: {avg_power_by_race.index[0]} ({avg_power_by_race.iloc[0]:.2f})\n")

# Optional bar chart
plt.figure(figsize=(8, 5))
avg_power_by_race.plot(kind='bar', color='steelblue')
plt.title('Average Power Score by Race')
plt.ylabel('Average Power Score')
plt.xlabel('Race')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('avg_power_by_race.png', dpi=150, bbox_inches='tight')
plt.show()

# ============================================================
# --- 2. Which stats are most linked to a specific role? ---
# ============================================================
stat_cols = ['level', 'strength', 'agility', 'intellect', 'stamina', 'magic_affinity', 'years_training']

# Average of each stat per role — shows which role excels where
role_stat_means = df.groupby('role')[stat_cols].mean()
print("Average stats by role:")
print(role_stat_means)

# Z-score normalize so stats on different scales are comparable
normalized = (role_stat_means - role_stat_means.mean()) / role_stat_means.std()

print("\nDominant stat per role (highest relative mean):")
for role in normalized.index:
    top_stat = normalized.loc[role].idxmax()
    print(f"  {role:<15} -> {top_stat}")

# --- Which feature is MOST effective overall (across all roles)? ---
# Uses feature_importances_ from the Decision Tree Classifier in Task 4
# Higher importance = the tree relies on that feature more to split/separate roles
print("\nFeature importance (Decision Tree Classifier predicting role):")
importance_ranked = sorted(zip(X.columns, tree_clf.feature_importances_), key=lambda x: -x[1])
for feat, imp in importance_ranked:
    print(f"  {feat:<20} {imp:.4f}")

most_effective_feature = importance_ranked[0][0]
print(f"\n>>> Most effective feature overall: {most_effective_feature}")

# Optional heatmap to visualize stat-role relationships
import seaborn as sns
plt.figure(figsize=(10, 6))
sns.heatmap(normalized, annot=True, cmap='coolwarm', center=0)
plt.title('Relative Stat Strength by Role (z-score normalized)')
plt.tight_layout()
plt.savefig('stat_role_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Quick look at both features vs Salary
plt.scatter(df['race'], df['role'], color='steelblue')
plt.xlabel('race')
plt.ylabel('role')
plt.show()

# Quick look at both features vs Salary
plt.scatter(df['level'], df['role'], color='steelblue')
plt.xlabel('level')
plt.ylabel('role')
plt.show()

# Quick look at both features vs Salary
plt.scatter(df['strength'], df['role'], color='steelblue')
plt.xlabel('strength')
plt.ylabel('role')
plt.show()

# Quick look at both features vs Salary
plt.scatter(df['agility'], df['role'], color='steelblue')
plt.xlabel('agility')
plt.ylabel('role')
plt.show()

"""# new model:"""

# ============================================================
# Random Forest Regressor — predicting power_score
# ============================================================

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Features
X = df.drop(columns=['power_score'])

# One-hot encode categorical features
X = pd.get_dummies(X, drop_first=True)

# Target MUST be numeric
y = df['power_score']

# Make sure power_score is numeric
y = pd.to_numeric(y, errors='coerce')

# Remove rows where target is missing/non-numeric
valid_rows = y.notna()
X = X.loc[valid_rows]
y = y.loc[valid_rows]

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Random Forest Regressor
rf_reg = RandomForestRegressor(
    n_estimators=100,
    max_depth=4,
    random_state=42
)

rf_reg.fit(X_train, y_train)

y_pred_rf = rf_reg.predict(X_test)

# R² Score
results['Random Forest Regressor'] = r2_score(y_test, y_pred_rf)

print("=== Random Forest Regressor ===")
print(f"R² Score: {results['Random Forest Regressor']:.4f}")

# ============================================================
# Updated comparison across all models
# ============================================================

print("\nR² Score Comparison (all models):")

for model, score in sorted(results.items(), key=lambda x: -x[1]):
    print(f"  {model:<30} {score:.4f}")

# ============================================================
# Feature Importance
# ============================================================

print("\nFeature Importance (Random Forest):")

for feat, imp in sorted(
    zip(X.columns, rf_reg.feature_importances_),
    key=lambda x: -x[1]
):
    print(f"  {feat:<20} {imp:.4f}")