# -*- coding: utf-8 -*-
"""students project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1j_HZ33Yruv0YFhEADN4IfLe1wRko-X

## Setup:
"""

# ── All imports in one place ──────────────────────────────────────────

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression, LogisticRegression

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    mean_absolute_error
)

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    log_loss,
    classification_report
)

from sklearn.preprocessing import LabelEncoder

from sklearn.tree import (
    DecisionTreeClassifier,
    plot_tree,
    export_text
)

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)


print('Ready ✅')

# Load dataset — each row is a student, each column is a feature
df = pd.read_csv('student_performance.csv')
print(f'Dataset: {df.shape[0]} students, {df.shape[1]} columns')
df.head(8)

# Quick look at both features vs Salary
plt.scatter(df['StudyHours'], df['FinalScore_Target_Regression'], color='steelblue')
plt.xlabel('StudyHours')
plt.ylabel('FinalScore_Target_Regression')
plt.show()

# Quick look at both features vs Salary
plt.scatter(df['Attendance'], df['FinalScore_Target_Regression'], color='steelblue')
plt.xlabel('Attendance')
plt.ylabel('FinalScore_Target_Regression')
plt.show()

"""## Linear Regrassion  :"""

from sklearn.model_selection import train_test_split
X = df[['StudyHours', 'Attendance', 'PrevExamScore', 'SleepHours']]
y = df['FinalScore_Target_Regression']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


print(f'Train: {len(X_train)} rows  |  Test: {len(X_test)} rows')

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.3f}")
print(f"MAE:  {mae:.3f}")
print(f"R²:   {r2:.3f}")

print("\nIntercept:", model.intercept_)
for feature, coef in zip(X.columns, model.coef_):
    print(f"  {feature:<16} {coef:.4f}")

def predict_score(study_hours, attendance_pct, prev_score, sleep_hours):
    new_student = pd.DataFrame([{
        'StudyHours': study_hours,
        'Attendance': attendance_pct,
        'PrevExamScore': prev_score,
        'SleepHours': sleep_hours
    }])

    predicted = model.predict(new_student)[0]
    return round(predicted, 2)

score = predict_score(
    study_hours=5,
    sleep_hours=7,
    attendance_pct=35,
    prev_score=90
)

print(f"Predicted final score: {score}")

"""## logistic Regression :"""

features = ['StudyHours', 'Attendance', 'PrevExamScore', 'SleepHours']
X_t = df[features]
y_t = df['Pass_Target_Logistic']

X_tr_t, X_te_t, y_tr_t, y_te_t = train_test_split(X_t, y_t, test_size=0.2, random_state=42)

# Scale features — important for logistic regression
scaler = StandardScaler()
X_tr_t_scaled = scaler.fit_transform(X_tr_t)
X_te_t_scaled = scaler.transform(X_te_t)

log_model = LogisticRegression()
log_model.fit(X_tr_t_scaled, y_tr_t)

print('Coefficients:')
for feat, coef in zip(features, log_model.coef_[0]):
    print(f'  {feat:<8}: {coef:>7.3f}')
print(f'  Intercept: {log_model.intercept_[0]:.3f}')

y_pred_t = log_model.predict(X_te_t_scaled)

accuracy = accuracy_score(y_te_t, y_pred_t)
print(f'Accuracy: {accuracy:.4f}  ({accuracy*100:.1f}% of passengers correctly classified)')

# Confusion matrix
cm = confusion_matrix(y_te_t, y_pred_t)

fig, ax = plt.subplots(figsize=(5, 4))
im = ax.imshow(cm, cmap='Blues')
ax.set_xticks([0, 1]); ax.set_yticks([0, 1])
ax.set_xticklabels(['Predicted: No', 'Predicted: Yes'])
ax.set_yticklabels(['Actual: No', 'Actual: Yes'])
for i in range(2):
    for j in range(2):
        ax.text(j, i, cm[i, j], ha='center', va='center', fontsize=14, color='black')
ax.set_title('Confusion Matrix')
plt.tight_layout()
plt.show()

# Predict probability for a new passenger
# 1st class, female, age 29, fare 80
new_Student = scaler.transform([[7, 65, 70, 7]])
prob = log_model.predict_proba(new_Student)[0][1]
print(f'success probability: {prob:.2%}')

"""## multi _ Class _ classification:"""

# How many students per grade?
df['Grade_Target_MultiClass'].value_counts()

# Prepare features and target for multi-class
# Features (X) = what the model uses to make a prediction
# Target (y)   = what we want to predict

X = df[['StudyHours', 'Attendance', 'PrevExamScore', 'SleepHours']]
y = df['Grade_Target_MultiClass']   # multi-class target: A / B / C / Fail


# Split: 80% to train the model, 20% to test it
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f'Training samples : {len(X_train)}')
print(f'Testing  samples : {len(X_test)}')

# Train a Logistic Regression model on 4 classes
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

print('Predictions for the first 10 test students:')
comparison = pd.DataFrame({'Actual': y_test.values[:10], 'Predicted': y_pred[:10]})
print(f'Actual: {y_test.values[:10]}')
print(f'Predicted: {y_pred[:10]}')

# The model can also give a PROBABILITY for each class
# This is the softmax output — all probabilities sum to 1

proba = model.predict_proba(X_test)

print('Predicted class probabilities for the first 5 students:')
proba.round(2)[:5]

# Cross-entropy loss — one line with sklearn
loss = log_loss(y_test, proba)
print(f'Cross-Entropy Loss: {loss:.4f}')
print()
print('Interpretation:')
print('  < 0.3  → model is very confident and mostly right')
print('  0.3–1  → decent, some uncertainty')
print('  > 1    → model is confused or overconfident in wrong answers')

"""### Confusion Matrix

Shows us **where** the model made mistakes — which classes it confused with each other.

- The **diagonal** = correct predictions ✅
- Everything **off-diagonal** = mistakes ❌
"""

# Confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=['A', 'B', 'C', 'Fail'])

plt.figure(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['A', 'B', 'C', 'Fail'])
disp.plot(cmap='Blues', colorbar=False)
plt.title('Confusion Matrix — Grade Prediction')
plt.tight_layout()
plt.show()

# Accuracy, Precision, Recall, F1 — all in one
print('=== Classification Report ===')
print(classification_report(y_test, y_pred, target_names=['A', 'B', 'C', 'Fail']))

print('=== Individual Metrics ===')
print(f'Accuracy  : {accuracy_score(y_test, y_pred):.2%}  — overall % correct')
print(f'Precision : {precision_score(y_test, y_pred, average="macro"):.2%}  — when it says a class, how often is it right?')
print(f'Recall    : {recall_score(y_test, y_pred, average="macro"):.2%}  — of the real class, how many did it catch?')
print(f'F1 Score  : {f1_score(y_test, y_pred, average="macro"):.2%}  — balance between precision & recall')

"""## Decision Tree :"""

# ============================================================
# 1. تحميل البيانات
# ============================================================

df = pd.read_csv('student_performance.csv')

X = df[['StudyHours', 'Attendance', 'PrevExamScore', 'SleepHours']]
y = df['Grade_Target_MultiClass']   # multi-class target: A / B / C / Fail

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ============================================================
# 2. بناء Decision Tree باستخدام Entropy (Cross-Entropy criterion)
# ============================================================

tree = DecisionTreeClassifier(
    criterion='entropy',   # ده اللي بيستخدم Information Gain المبني على Entropy
    max_depth=4,
    random_state=42
)

tree.fit(X_train, y_train)


# ============================================================
# 3. التقييم
# ============================================================

y_pred = tree.predict(X_test)

acc = accuracy_score(y_test, y_pred)

print(f"Accuracy: {acc:.3f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix (rows=actual, cols=predicted):")

labels = sorted(y.unique())

cm = confusion_matrix(y_test, y_pred, labels=labels)

print(pd.DataFrame(cm, index=labels, columns=labels))


# ============================================================
# 4. عرض شجرة القرار كـ نص (يوضح كل split)
# ============================================================

print("\n--- Tree structure ---")
print(export_text(tree, feature_names=list(X.columns)))


# ============================================================
# 5. Feature Importance
# ============================================================

print("Feature Importance:")

for feat, imp in sorted(
    zip(X.columns, tree.feature_importances_),
    key=lambda x: -x[1]
):
    print(f"  {feat:<16} {imp:.4f}")


# ============================================================
# 6. حساب الـ Entropy الابتدائي يدويًا (زي ما الدكتور بيشرح)
# ============================================================

def entropy(y_series):
    probs = y_series.value_counts(normalize=True)
    return -np.sum(probs * np.log2(probs))


root_entropy = entropy(y_train)

print(f"\nRoot node entropy: {root_entropy:.4f} bits")


# ============================================================
# 7. رسم الشجرة
# ============================================================

plt.figure(figsize=(20, 10))

plot_tree(
    tree,
    feature_names=X.columns,
    class_names=tree.classes_,
    filled=True,
    rounded=True,
    fontsize=9
)

plt.title(
    "Decision Tree (Entropy Criterion) - Predicting Student Grade",
    fontsize=14
)

plt.tight_layout()

plt.savefig(
    'decision_tree.png',
    dpi=150,
    bbox_inches='tight'
)